# Generated by Django 5.1.1 on 2024-09-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_quotes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="quote",
            name="tags",
        ),
        migrations.AddField(
            model_name="quote",
            name="tags",
            field=models.ManyToManyField(to="app_quotes.tag"),
        ),
    ]
