# Generated by Django 5.1.1 on 2024-09-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_quotes", "0002_tag_remove_quote_tags_quote_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="born_date",
            field=models.CharField(max_length=255),
        ),
    ]
